# Generated by Django 5.2.11 on 2026-02-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('TEMP_HUMI', '温湿度传感器'), ('LIGHT', '光照传感器'), ('PRESSURE', '气压传感器'), ('LAMP_SWITCH', '灯具开关'), ('AC_SWITCH', '空调开关'), ('PIR', '人体感应'), ('FAN_SWITCH', '风扇开关'), ('SMOKE', '烟雾传感器')], max_length=32, verbose_name='设备类型')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='位置/房间')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('current_state', models.JSONField(blank=True, default=dict, verbose_name='当前状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('data', models.JSONField(verbose_name='数据内容')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='devices.device')),
            ],
            options={
                'verbose_name': '设备历史数据',
                'verbose_name_plural': '设备历史数据',
                'ordering': ['-timestamp'],
            },
        ),
    ]
