# Generated by Django 5.2.11 on 2026-02-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否为公共设备'),
        ),
    ]
