"""
Django settings for smart_home_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()   # 加载 .env 变量


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    host for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    # Local apps
    'accounts',
    'devices',
    'logs_app',
    'scenes',
    'mqtt_gateway',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smart_home_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_home_backend.wsgi.application'
ASGI_APPLICATION = 'smart_home_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# New setup, use MariaDB

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'iot_data'),  # 第二个参数是默认值
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        # 推荐配置：确保严格模式，防止数据截断等问题
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Old setup, use sqlite3

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==== REST framework & JWT ====

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from corsheaders.defaults import default_headers  # type: ignore

CORS_ALLOW_ALL_ORIGINS = _env_bool("DJANGO_CORS_ALLOW_ALL_ORIGINS", False)
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
    CORS_ALLOWED_ORIGINS = [o for o in CORS_ALLOWED_ORIGINS if o]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
]

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==== Security 基础加固（不改变业务逻辑） ====

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# SSE 临时票据（短时一次性）配置
REALTIME_STREAM_TOKEN_TTL_SECONDS = int(os.getenv('REALTIME_STREAM_TOKEN_TTL_SECONDS', '30'))
REALTIME_STREAM_ALLOW_LEGACY_ACCESS_TOKEN_QUERY = _env_bool(
    'REALTIME_STREAM_ALLOW_LEGACY_ACCESS_TOKEN_QUERY',
    False,
)

# ==== MQTT 模拟设备配置 ====

MQTT_CONFIG = {
    'HOST': os.getenv('MQTT_HOST', '127.0.0.1'),
    'PORT': int(os.getenv('MQTT_PORT', 1883)),
    'USERNAME': os.getenv('MQTT_USER'),
    'PASSWORD': os.getenv('MQTT_PASSWORD'),
    'KEEPALIVE': 60,
    'TOPIC_PREFIX': 'home',
    # TLS / mqtts
    'USE_TLS': os.getenv('MQTT_USE_TLS', 'False').lower() in ('true', '1', 'yes'),
    'CA_CERTS': os.getenv('MQTT_CA_CERTS') or None,
    'CERTFILE': os.getenv('MQTT_CERTFILE') or None,
    'KEYFILE': os.getenv('MQTT_KEYFILE') or None,
    'TLS_INSECURE': os.getenv('MQTT_TLS_INSECURE', 'False').lower() in ('true', '1', 'yes'),
}

# ==== Email ====

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# ==== Energy（估算能耗） ====

# 固定电价（元/kWh）
ENERGY_PRICE_PER_KWH = float(os.getenv('ENERGY_PRICE_PER_KWH', '0.66'))

# 设备功率估算参数（W）
ENERGY_POWER_PROFILE = {
    # 灯具开关
    'LAMP_ON_W': float(os.getenv('ENERGY_LAMP_ON_W', '9')),
    # 风扇档位
    'FAN_SPEED_1_W': float(os.getenv('ENERGY_FAN_SPEED_1_W', '30')),
    'FAN_SPEED_2_W': float(os.getenv('ENERGY_FAN_SPEED_2_W', '45')),
    'FAN_SPEED_3_W': float(os.getenv('ENERGY_FAN_SPEED_3_W', '60')),
    # 空调：按温度做线性估算并做上下限夹取
    'AC_BASE_W': float(os.getenv('ENERGY_AC_BASE_W', '900')),
    'AC_TEMP_STEP_W': float(os.getenv('ENERGY_AC_TEMP_STEP_W', '25')),
    'AC_MIN_W': float(os.getenv('ENERGY_AC_MIN_W', '500')),
    'AC_MAX_W': float(os.getenv('ENERGY_AC_MAX_W', '1500')),
    # 传感器待机功耗（可选）
    'SENSOR_IDLE_W': float(os.getenv('ENERGY_SENSOR_IDLE_W', '0.5')),
}
