# Generated by Django 5.2.11 on 2026-02-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('trigger_type', models.CharField(choices=[('THRESHOLD_ABOVE', '高于阈值'), ('THRESHOLD_BELOW', '低于阈值'), ('RANGE_OUT', '超出范围'), ('TIME_STATE', '时间+状态组合')], max_length=32, verbose_name='触发类型')),
                ('trigger_field', models.CharField(help_text='例如：temp（温度）、humi（湿度）', max_length=50, verbose_name='触发字段')),
                ('trigger_value', models.JSONField(help_text='阈值或范围值', verbose_name='触发值')),
                ('trigger_time_start', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('trigger_time_end', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('trigger_state_value', models.JSONField(blank=True, help_text='例如：{"on": true}', null=True, verbose_name='状态值')),
                ('action_type', models.CharField(choices=[('TOGGLE', '切换开关'), ('SET_TEMP', '设置温度'), ('SET_FAN_SPEED', '设置风扇档位'), ('TURN_ON', '开启设备'), ('TURN_OFF', '关闭设备')], max_length=32, verbose_name='动作类型')),
                ('action_value', models.JSONField(blank=True, help_text='例如：温度值（数字）或风扇档位（1/2/3）', null=True, verbose_name='动作值')),
                ('debounce_seconds', models.IntegerField(default=60, verbose_name='防抖时间（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='最后触发时间')),
                ('action_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_rules', to='devices.device', verbose_name='执行设备')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_rules', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('trigger_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='devices.device', verbose_name='触发设备')),
                ('trigger_state_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_rules', to='devices.device', verbose_name='状态设备')),
            ],
            options={
                'verbose_name': '场景规则',
                'verbose_name_plural': '场景规则',
                'ordering': ['-created_at'],
            },
        ),
    ]
