# Generated by Django 5.2.11 on 2026-02-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARN', '警告'), ('ERROR', '错误')], default='INFO', max_length=10, verbose_name='级别')),
                ('source', models.CharField(default='SYSTEM', max_length=50, verbose_name='来源')),
                ('message', models.TextField(verbose_name='消息')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
