# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_is_public"),
        ("logs_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAlertRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("preset", models.CharField(choices=[("temp_high", "温度过高"), ("temp_low", "温度过低"), ("humi_high", "湿度过高"), ("humi_low", "湿度过低"), ("smoke", "烟雾告警"), ("custom", "自定义")], default="temp_high", max_length=32, verbose_name="预设类型")),
                ("trigger_field", models.CharField(default="temp", help_text="temp / humi / smoke 等", max_length=32, verbose_name="触发字段")),
                ("trigger_value", models.FloatField(blank=True, help_text="超过或低于此值即触发", null=True, verbose_name="触发阈值")),
                ("trigger_above", models.BooleanField(default=True, help_text="True=高于触发，False=低于触发", verbose_name="高于阈值触发")),
                ("recipients", models.JSONField(default=list, help_text='["admin@example.com", "user@example.com"]', verbose_name="收件邮箱列表")),
                ("cc_list", models.JSONField(blank=True, default=list, verbose_name="抄送列表")),
                ("subject_template", models.CharField(default="[智能家居告警] {preset} - {device_name}", max_length=200, verbose_name="邮件主题")),
                ("body_template", models.TextField(default="触发设备：{device_name}\n触发条件：{preset}\n当前值：{value}\n时间：{time}", verbose_name="邮件正文模板")),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True, verbose_name="最后触发时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trigger_device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_alert_rules", to="devices.device", verbose_name="触发设备")),
            ],
            options={
                "verbose_name": "邮件告警规则",
                "verbose_name_plural": "邮件告警规则",
                "ordering": ["-created_at"],
            },
        ),
    ]
